### ISSUE TITLE
[1.19.2] Server Config options do not work

### ISSUE THREAD

**Issue by Reshirou** [superlord9362/WildLands#1]
Tested with NOTHING but Wild Lands and Terrablender- setting any generation settings to False simply does not work.

**Comment by SaltSouls** [comment]
Can confirm this. Even when setting them in the default configs folder, it doesn't respect the config file when loading a new world.

**Comment by Milanovsk1** [comment]
I'm having this same issue..

**Comment by superlord9362** [comment]
Fixed for upcoming update
